import { ArrowUpRight, Check, Quote } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { Footer } from "./Home";

function PageHeader({ number, label, title, intro }: { number: string; label: string; title: React.ReactNode; intro: string }) {
  return <section className="page-hero page-width"><div className="page-hero-meta"><span>{number}</span><span>{label}</span></div><h1>{title}</h1><p>{intro}</p></section>;
}
function Header() { return <header className="site-header page-width"><Link href="/" className="brand-lockup"><img src="/manus-storage/cobra-logo_d1e71238.png" alt="Cobra crest" /><span><small>THE</small> COBRA</span></Link><nav className="desktop-page-nav"><Link href="/academy">Academy</Link><Link href="/training">Training</Link><Link href="/gallery">Gallery</Link><Link href="/attendance">Attendance</Link><Link className="nav-cta" href="/contact">Start here <ArrowUpRight size={14} /></Link></nav></header>; }
export default function Academy() { const { data: content } = trpc.content.get.useQuery(); return <div className="site-shell"><Header /><main><PageHeader number="01" label="The academy" title={<>A practice built<br /><em>for the long game.</em></>} intro={content?.intro ?? "A modern martial arts academy built around quiet confidence, technical excellence, and the work no one sees."} /><section className="section page-width academy-story"><div className="story-visual"><img src="/manus-storage/dojo-space_e988f290.jpg" alt="Modern martial arts dojo" /><span>THE ROOM / THE RITUAL / THE RETURN</span></div><div className="story-copy"><div className="section-label"><span />Our story</div><h2>Leave the ego<br /><em>at the door.</em></h2><p className="lead">{content?.story}</p><p>{content?.mission}</p><div className="values-list"><div><strong>01</strong><span>Presence</span><p>Meet the moment in front of you.</p></div><div><strong>02</strong><span>Precision</span><p>Make the small details count.</p></div><div><strong>03</strong><span>Progress</span><p>Return often enough to change.</p></div></div></div></section><section className="section red-band"><div className="page-width red-band-inner"><Quote size={36} /><blockquote>“The goal is not to look like a fighter.<br />It is to become harder to break.”</blockquote><span>— THE COBRA STANDARD</span></div></section><section className="section page-width coach-section"><div><div className="section-label"><span />The coach</div><h2>Guidance with<br /><em>standards.</em></h2></div><div className="coach-card"><div className="coach-avatar">C</div><div><h3>{content?.coachName}</h3><p>{content?.coachBio}</p><Link className="text-link" href="/contact">Ask a question <ArrowUpRight size={15} /></Link></div></div></section><section className="section page-width journey"><div className="section-label"><span />The journey</div><h2>One step. Then<br /><em>another.</em></h2><div className="journey-line"><div><span>START</span><strong>01</strong><p>Show up curious.</p></div><div><span>BUILD</span><strong>02</strong><p>Learn the language.</p></div><div><span>LEAD</span><strong>03</strong><p>Carry the standard.</p></div></div><Link className="button button-primary" href="/contact">Begin your journey <ArrowUpRight size={16} /></Link></section></main><Footer content={content} /></div>; }
