import { ArrowLeft, CalendarCheck, Download, FileText, LayoutDashboard, LogIn, Plus, Save, ShieldCheck, UserPlus, UsersRound } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

type Panel = "overview" | "content" | "add-student" | "students" | "mark-attendance" | "history";

export default function Admin() {
  const { user, loading, isAuthenticated, logout } = useAuth();
  const coachSession = trpc.auth.coachSession.useQuery();
  const isAdmin = Boolean(isAuthenticated && user?.role === "admin");
  const hasCoachAccess = Boolean(isAdmin || coachSession.data);
  const [panel, setPanel] = useState<Panel>("overview");
  const contentQuery = trpc.content.get.useQuery(undefined, { enabled: hasCoachAccess });
  const studentsQuery = trpc.attendance.listStudents.useQuery(undefined, { enabled: hasCoachAccess });
  const historyQuery = trpc.attendance.history.useQuery(undefined, { enabled: hasCoachAccess });
  const coachLogin = trpc.auth.coachLogin.useMutation({ onSuccess: () => { toast.success("Coach access granted."); coachSession.refetch(); }, onError: error => toast.error(error.message) });
  const coachLogout = trpc.auth.coachLogout.useMutation({ onSuccess: () => coachSession.refetch() });
  const contentMutation = trpc.content.update.useMutation({ onSuccess: () => { toast.success("Website content saved."); contentQuery.refetch(); }, onError: error => toast.error(error.message) });
  const studentMutation = trpc.attendance.saveStudent.useMutation({ onSuccess: () => { toast.success("Student saved."); studentsQuery.refetch(); setPanel("students"); }, onError: error => toast.error(error.message) });
  const attendanceMutation = trpc.attendance.mark.useMutation({ onSuccess: () => { toast.success("Attendance saved."); historyQuery.refetch(); }, onError: error => toast.error(error.message) });
  const [credentials, setCredentials] = useState({ username: "", password: "" });
  const [student, setStudent] = useState({ studentId: "", name: "", belt: "" });
  const [attendance, setAttendance] = useState({ studentId: "", date: new Date().toISOString().slice(0, 10), status: "present" as "present" | "absent" | "late" });
  const [contentForm, setContentForm] = useState({ headline: "", intro: "", story: "", mission: "", coachName: "", coachBio: "", footer: "" });
  useEffect(() => { const data = contentQuery.data; if (data) setContentForm(current => ({ headline: current.headline || data.headline, intro: current.intro || data.intro, story: current.story || data.story, mission: current.mission || data.mission, coachName: current.coachName || data.coachName, coachBio: current.coachBio || data.coachBio, footer: current.footer || data.footer })); }, [contentQuery.data]);
  const studentOptions = useMemo(() => studentsQuery.data ?? [], [studentsQuery.data]);
  if (loading || (isAuthenticated === undefined && coachSession.isLoading)) return <div className="admin-gate"><div className="loader-line" /><p>Checking coach access...</p></div>;
  if (!hasCoachAccess) return <div className="admin-gate"><div className="admin-gate-mark"><ShieldCheck size={25} /></div><span className="eyebrow">THE COBRA / COACH PORTAL</span><h1>Private access<br /><em>for the coach.</em></h1><p>Sign in with the credentials provided by the academy owner to manage the public experience.</p><form className="coach-login-form" onSubmit={event => { event.preventDefault(); coachLogin.mutate(credentials); }}><label>Username<input value={credentials.username} onChange={event => setCredentials({ ...credentials, username: event.target.value })} autoComplete="username" placeholder="Coach username" required /></label><label>Password<input type="password" value={credentials.password} onChange={event => setCredentials({ ...credentials, password: event.target.value })} autoComplete="current-password" placeholder="Coach password" required /></label><button className="button button-primary" type="submit" disabled={coachLogin.isPending}><LogIn size={16} /> {coachLogin.isPending ? "Verifying..." : "Coach login"}</button></form><Link className="back-link" href="/"><ArrowLeft size={14} /> Back to site</Link></div>;
  if (!isAdmin && !coachSession.data) return <div className="admin-gate"><div className="admin-gate-mark"><ShieldCheck size={25} /></div><span className="eyebrow">ACCESS RESTRICTED</span><h1>This room is<br /><em>coach-only.</em></h1><p>Your account is signed in, but it has not been granted admin access.</p><button className="button button-dark" onClick={() => logout()}>Sign out</button><Link className="back-link" href="/"><ArrowLeft size={14} /> Back to site</Link></div>;
  const saveContent = (event: FormEvent) => { event.preventDefault(); if (!contentQuery.data) return; contentMutation.mutate({ payload: { ...contentQuery.data, ...contentForm } }); };
  const signOut = () => { if (coachSession.data) coachLogout.mutate(); else logout(); };
  const nav = (next: Panel) => setPanel(next);
  return <div className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="admin-brand"><img src="/manus-storage/cobra-logo_d1e71238.png" alt="Cobra crest" /><div><strong>THE COBRA</strong><span>COACH PORTAL</span></div></Link><div className="admin-nav"><span className="admin-nav-label">Menu</span><button className={panel === "overview" ? "active" : ""} onClick={() => nav("overview")}><LayoutDashboard size={16} /> Dashboard</button><button className={panel === "content" ? "active" : ""} onClick={() => nav("content")}><FileText size={16} /> Website content</button><button className={panel === "add-student" ? "active" : ""} onClick={() => nav("add-student")}><UserPlus size={16} /> Add student</button><button className={panel === "students" ? "active" : ""} onClick={() => nav("students")}><UsersRound size={16} /> All students</button><button className={panel === "mark-attendance" ? "active" : ""} onClick={() => nav("mark-attendance")}><CalendarCheck size={16} /> Mark attendance</button><button className={panel === "history" ? "active" : ""} onClick={() => nav("history")}><FileText size={16} /> Attendance history</button></div><div className="admin-sidebar-bottom"><Link href="/"><ArrowLeft size={15} /> Public site</Link><button onClick={signOut}>Sign out</button></div></aside><main className="admin-main"><div className="admin-topbar"><div><span className="eyebrow">COACH DASHBOARD</span><h1>{panelTitle(panel)}</h1></div><span className="admin-user"><span className="online-dot" /> Coach mode</span></div>{panel === "overview" && <Overview students={studentOptions.length} history={historyQuery.data?.length ?? 0} onNavigate={nav} />}{panel === "content" && <ContentPanel form={contentForm} setForm={setContentForm} onSave={saveContent} saving={contentMutation.isPending} />}{panel === "add-student" && <AddStudent student={student} setStudent={setStudent} onSave={() => studentMutation.mutate({ ...student, enabled: 1 })} saving={studentMutation.isPending} />}{panel === "students" && <StudentsPanel students={studentOptions} onAdd={() => nav("add-student")} />}{panel === "mark-attendance" && <MarkAttendancePanel students={studentOptions} attendance={attendance} setAttendance={setAttendance} onSave={() => { if (!attendance.studentId) { toast.error("Select a student first."); return; } attendanceMutation.mutate(attendance); }} saving={attendanceMutation.isPending} />}{panel === "history" && <HistoryPanel rows={historyQuery.data ?? []} />}</main></div>;
}

function panelTitle(panel: Panel) { return { overview: "Dashboard", content: "Edit website content", "add-student": "Add student", students: "All students", "mark-attendance": "Mark attendance", history: "Attendance history" }[panel]; }
function Overview({ students, history, onNavigate }: { students: number; history: number; onNavigate: (panel: Panel) => void }) { return <section className="admin-overview"><div className="dashboard-welcome"><span className="eyebrow">WELCOME BACK, COACH</span><h2>Keep the dojo<br /><em>moving.</em></h2><p>Everything you need is in the menu. No coding required.</p></div><div className="dashboard-cards"><button onClick={() => onNavigate("students")}><UsersRound size={20} /><strong>{students}</strong><span>All students</span></button><button onClick={() => onNavigate("history")}><CalendarCheck size={20} /><strong>{history}</strong><span>Attendance records</span></button><button onClick={() => onNavigate("add-student")}><UserPlus size={20} /><strong>+</strong><span>Add a student</span></button><button onClick={() => onNavigate("content")}><FileText size={20} /><strong>EDIT</strong><span>Website content</span></button></div><div className="quick-actions"><h3>Quick actions</h3><button className="button button-primary" onClick={() => onNavigate("mark-attendance")}><CalendarCheck size={16} /> Mark today’s attendance</button><button className="button button-dark" onClick={() => onNavigate("history")}><Download size={16} /> Download attendance</button></div></section>; }
function ContentPanel({ form, setForm, onSave, saving }: any) { const update = (key: string, value: string) => setForm({ ...form, [key]: value }); return <section className="admin-panel"><p className="panel-help">Fill in the boxes below and press save. You do not need to edit code.</p><form className="simple-content-form" onSubmit={onSave}><label>Main headline<input value={form.headline} onChange={e => update("headline", e.target.value)} /></label><label>Homepage introduction<textarea value={form.intro} onChange={e => update("intro", e.target.value)} /></label><label>Academy story<textarea value={form.story} onChange={e => update("story", e.target.value)} /></label><label>Mission statement<textarea value={form.mission} onChange={e => update("mission", e.target.value)} /></label><label>Coach name<input value={form.coachName} onChange={e => update("coachName", e.target.value)} /></label><label>Coach bio<textarea value={form.coachBio} onChange={e => update("coachBio", e.target.value)} /></label><label>Footer line<input value={form.footer} onChange={e => update("footer", e.target.value)} /></label><button className="button button-primary" type="submit" disabled={saving}><Save size={16} /> {saving ? "Saving..." : "Save website content"}</button></form></section>; }
function AddStudent({ student, setStudent, onSave, saving }: any) { return <section className="admin-panel"><p className="panel-help">Add the student once. The Student ID is what they will use to check attendance.</p><div className="simple-form"><label>Student roll ID<input value={student.studentId} onChange={e => setStudent({ ...student, studentId: e.target.value })} placeholder="COBRA-001" /></label><label>Student name<input value={student.name} onChange={e => setStudent({ ...student, name: e.target.value })} placeholder="Full name" /></label><label>Belt<input value={student.belt} onChange={e => setStudent({ ...student, belt: e.target.value })} placeholder="White / Yellow / Black" /></label><button className="button button-primary" type="button" onClick={onSave} disabled={saving}><Plus size={16} /> {saving ? "Saving..." : "Add student"}</button></div></section>; }
function StudentsPanel({ students, onAdd }: any) { return <section className="admin-panel"><div className="panel-heading"><p className="panel-help">Every active student is listed here.</p><button className="button button-primary" onClick={onAdd}><Plus size={16} /> Add student</button></div><div className="data-table"><div className="data-table-head"><span>Student name</span><span>Roll ID</span><span>Belt</span><span>Status</span></div>{students.length ? students.map((student: any) => <div className="data-table-row" key={student.studentId}><strong>{student.name}</strong><span>{student.studentId}</span><span>{student.belt}</span><b>Active</b></div>) : <div className="empty-data">No students added yet.</div>}</div></section>; }
function MarkAttendancePanel({ students, attendance, setAttendance, onSave, saving }: any) { return <section className="admin-panel"><p className="panel-help">Choose a student, select the date, mark the status, and save. Saving the same student/date updates the record.</p><div className="simple-form attendance-form"><label>Student<select value={attendance.studentId} onChange={e => setAttendance({ ...attendance, studentId: e.target.value })}><option value="">Select student</option>{students.map((student: any) => <option key={student.studentId} value={student.studentId}>{student.name} — {student.studentId}</option>)}</select></label><label>Date<input type="date" value={attendance.date} onChange={e => setAttendance({ ...attendance, date: e.target.value })} /></label><label>Status<select value={attendance.status} onChange={e => setAttendance({ ...attendance, status: e.target.value })}><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option></select></label><button className="button button-primary" type="button" onClick={onSave} disabled={saving}><Save size={16} /> Save attendance</button></div></section>; }
function HistoryPanel({ rows }: { rows: any[] }) { const download = () => { const header = "Student Name,Roll ID,Belt,Date,Status\n"; const csv = header + rows.map(row => [row.studentName, row.studentId, row.belt, row.date, row.status].map((value: string) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `cobra-attendance-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); }; return <section className="admin-panel"><div className="panel-heading"><p className="panel-help">All attendance records, newest first.</p><button className="button button-primary" onClick={download} disabled={!rows.length}><Download size={16} /> Download Excel file</button></div><div className="data-table attendance-history"><div className="data-table-head"><span>Student name</span><span>Roll ID</span><span>Date</span><span>Status</span></div>{rows.length ? rows.map(row => <div className="data-table-row" key={`${row.studentId}-${row.date}`}><strong>{row.studentName}</strong><span>{row.studentId}</span><span>{row.date}</span><b className={`status-${row.status}`}>{row.status}</b></div>) : <div className="empty-data">No attendance marked yet.</div>}</div></section>; }
